<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.252" ExcludeAssets="runtime" />
    <Reference Include="StoreApi">
      <HintPath>.\StoreApi.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
